development:
  dialect: postgres
  database: cover
  user: cover
  password: cover
  host: db
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://cover:cover@testdb:5432/cover_test?sslmode=disable"}}

staging:
  url: {{envOr "DATABASE_URL" "postgres://cover:cover@127.0.0.1:5432/cover_staging?sslmode=disable"}}

prod:
  url: {{envOr "DATABASE_URL" "postgres://cover:cover@127.0.0.1:5432/cover_production?sslmode=disable"}}
