FROM gobuffalo/buffalo:v0.18.8

# Set file permissions so non-root user can access them -- necessary if USER user is enabled below
# RUN chmod -R o=,g=rwX $GOPATH/pkg

RUN apt-get update && apt-get install -y \
    nano \
    curl \
    netcat \
    && apt-get clean

# Install the desired version of NodeJS
RUN npm cache clean -f && \
    npm install -g n && \
    n 16

RUN curl -o /usr/local/bin/whenavail https://bitbucket.org/silintl/docker-whenavail/raw/1.0.2/whenavail \
     && chmod a+x /usr/local/bin/whenavail

RUN mkdir -p /cover
WORKDIR /cover

# These lines (uncommented) seem to break permissions on Ubuntu
#RUN useradd user && usermod -a -G root user && mkdir /home/user && chown user.user /home/user
#USER user

# Copy the Go Modules manifests
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

# additional deps needed for running tests
RUN go get github.com/gobuffalo/suite/v3 \
  github.com/gobuffalo/httptest \
  github.com/markbates/grift \
  github.com/stretchr/testify \
  github.com/gorilla/pat \
  github.com/gorilla/context
RUN CGO_ENABLED=0 go get -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv

ADD . .

RUN printf "t() {\n go test -v -tags development ./\$1 -testify.m \$2 \n}\n" >> ~/.bashrc

EXPOSE 6060
CMD ["buffalo", "dev"]
