FROM gobuffalo/buffalo:v0.16.26

# Set file permissions so non-root user can access them -- necessary if USER user is enabled below
# RUN chmod -R o=,g=rwX $GOPATH/pkg

RUN apt-get update && apt-get install -y \
    nano \
    curl \
    netcat \
    && apt-get clean

RUN curl -o /usr/local/bin/whenavail https://bitbucket.org/silintl/docker-whenavail/raw/1.0.2/whenavail \
     && chmod a+x /usr/local/bin/whenavail

RUN mkdir -p /riskman
WORKDIR /riskman

COPY go.* ./
RUN chmod 660 /riskman/go.* && chmod 770 /riskman
ENV GO111MODULE=on

#RUN useradd user && usermod -a -G root user && mkdir /home/user && chown user.user /home/user
#USER user

# additional deps needed for running tests
RUN go get github.com/gobuffalo/suite/v3 \
  github.com/gobuffalo/httptest \
  github.com/markbates/grift \
  github.com/stretchr/testify \
  github.com/gorilla/pat \
  github.com/gorilla/context

ADD . .
RUN go get ./...

EXPOSE 6060
CMD ["buffalo", "dev"]
