FROM golang:1.22

ENV REFRESHED_AT=2024-03-13

EXPOSE 3000

ENV GOPROXY=https://proxy.golang.org

# Installing buffalo binary
RUN go install github.com/gobuffalo/cli/cmd/buffalo@latest
RUN go install github.com/gobuffalo/buffalo-pop/v3@latest

# Set file permissions so non-root user can access them -- necessary if USER user is enabled below
# RUN chmod -R o=,g=rwX $GOPATH/pkg

RUN apt-get update && apt-get install -y \
    netcat-traditional \
    postgresql \
    && apt-get clean

ADD https://raw.githubusercontent.com/silinternational/whenavail-script/1.0.2/whenavail /usr/local/bin/whenavail
RUN chmod a+x /usr/local/bin/whenavail

RUN mkdir -p /cover
WORKDIR /cover

# These lines (uncommented) seem to break permissions on Ubuntu
#RUN useradd user && usermod -a -G root user && mkdir /home/user && chown user.user /home/user
#USER user

# Copy the Go Modules manifests
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

# additional deps needed for running tests
RUN go get github.com/gobuffalo/suite/v3 \
  github.com/gobuffalo/httptest \
  github.com/markbates/grift \
  github.com/stretchr/testify \
  github.com/gorilla/pat \
  github.com/gorilla/context

# install dlv for debugging
RUN go install github.com/go-delve/delve/cmd/dlv@v1.9.0

ADD . .

RUN printf "t() {\n go test -v -tags development ./\$1 -testify.m \$2 \n}\n" >> ~/.bashrc

EXPOSE 6060
CMD ["buffalo", "dev"]
