version: "3"

services:
  app:
    build:
      context: application
      dockerfile: Dockerfile-dev
    depends_on:
      - testdb
      - minio
    environment:
      ADDR: 0.0.0.0
      HOST: http://cover.local:3000
      PORT: 3000
      DOCKER_IP: testdb
      GO_ENV: test
      TEST_DATABASE_URL: postgres://cover:cover@testdb:5432/cover_test?sslmode=disable
      API_BASE_URL: http://cover.local:3000
      APP_NAME: Cover
      SESSION_SECRET: kljsLSDJ83jF^kj3LKNEKn435LDKnt
      AWS_ACCESS_KEY_ID: abc123
      AWS_SECRET_ACCESS_KEY: abcd1234
      AWS_REGION: us-east-1
      AWS_S3_ENDPOINT: http://minio:9000
      AWS_S3_DISABLE_SSL: 1
      AWS_S3_BUCKET: cover-test-bucket
      EMAIL_FROM_ADDRESS: no_reply@example.com
      EMAIL_SERVICE: dummy
      SAML_SP_ENTITY_ID: http://example.local:3000
      SAML_AUDIENCE_URI: http://example.local:3000
      SAML_IDP_ENTITY_ID: our.idp.net
      SAML_IDP_CERT: MIID9zCCAt+gAwIBAgIUaI7AYP1KK65v4CK95oLkOiZ1TR4wDQYJKoZIhvcNAQELBQAwgYoxCzAJBgNVBAYTAlJVMRAwDgYDVQQIDAdVa3JhaW5lMQ0wCwYDVQQHDARLaWV2MQwwCgYDVQQKDANHUlUxETAPBgNVBAsMCHdoYXRldmVyMREwDwYDVQQDDAhKb2huIERvZTEmMCQGCSqGSIb3DQEJARYXam9obl9kb2U5OTlAZXhhbXBsZS5vcmcwHhcNMjEwOTIyMTIyNzU1WhcNMzEwOTIyMTIyNzU1WjCBijELMAkGA1UEBhMCUlUxEDAOBgNVBAgMB1VrcmFpbmUxDTALBgNVBAcMBEtpZXYxDDAKBgNVBAoMA0dSVTERMA8GA1UECwwId2hhdGV2ZXIxETAPBgNVBAMMCEpvaG4gRG9lMSYwJAYJKoZIhvcNAQkBFhdqb2huX2RvZTk5OUBleGFtcGxlLm9yZzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK+He1K3Sf4CGqQPyKEpNRVUN/77cDihsE7RS/12IdnXcQu9p3LRfYUnp/1kmqocBxjrBJfBGsUzvpultxny1wa2aUNNVaIXIAc0Sx/dRyuwHzsLhl40CDiiuxgJZfZXOMhPCFlV1GukuOmBloxKepGwYalMOqMq3Lik0qr2lsxX7Z+iADds5IaWr65sI5WDlEEBazCiAg9diQ0la8UHOOpaYRDyUFyKVCPdY5vyulnxpp1lncxO234ez64D2IXTIpS9PCJGk3H8WM5vA3rZNNSoiqjwaYNoPI5qmqUW49DeeLKeUQ+lDZS97o4V3VhBGv7WxDWFJYVFddPykRCu+GMCAwEAAaNTMFEwHQYDVR0OBBYEFCDaQ6/Lgkk2a43bTuzgbtlyHTrbMB8GA1UdIwQYMBaAFCDaQ6/Lgkk2a43bTuzgbtlyHTrbMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBACgT/c1zUSj3VIbsNRSmR9e90YWKr648S0hx2ciJTr7MPlYOzE3/+wrBul1+bjqJr6wnul1NIM3KRD733nvMKEo6BkfAtRWuQfKaYJwn6JtVBk1KYdTTFEQN5xP3WwWNP9ZaOgTBaSB7tpq4TllC20hnwQaopuRhmEDoY9bOSbVlh6sSoJvZdbphpco470FHY5kLpp/Mj/aqehQ18ADyuviJU9U0eUB+V94pkoFPywo+/C/+y3QwW8+iDCuWzaoZTHWUcBtWQYqkGFAC7XOnILORBpz6yGmMRoekUeU7a/5hstC1wToxJEHpnlAicYp9LyWVg58hUEAJUsZj2yYe7vI=
      SAML_SP_CERT: MIID9zCCAt+gAwIBAgIUaI7AYP1KK65v4CK95oLkOiZ1TR4wDQYJKoZIhvcNAQELBQAwgYoxCzAJBgNVBAYTAlJVMRAwDgYDVQQIDAdVa3JhaW5lMQ0wCwYDVQQHDARLaWV2MQwwCgYDVQQKDANHUlUxETAPBgNVBAsMCHdoYXRldmVyMREwDwYDVQQDDAhKb2huIERvZTEmMCQGCSqGSIb3DQEJARYXam9obl9kb2U5OTlAZXhhbXBsZS5vcmcwHhcNMjEwOTIyMTIyNzU1WhcNMzEwOTIyMTIyNzU1WjCBijELMAkGA1UEBhMCUlUxEDAOBgNVBAgMB1VrcmFpbmUxDTALBgNVBAcMBEtpZXYxDDAKBgNVBAoMA0dSVTERMA8GA1UECwwId2hhdGV2ZXIxETAPBgNVBAMMCEpvaG4gRG9lMSYwJAYJKoZIhvcNAQkBFhdqb2huX2RvZTk5OUBleGFtcGxlLm9yZzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK+He1K3Sf4CGqQPyKEpNRVUN/77cDihsE7RS/12IdnXcQu9p3LRfYUnp/1kmqocBxjrBJfBGsUzvpultxny1wa2aUNNVaIXIAc0Sx/dRyuwHzsLhl40CDiiuxgJZfZXOMhPCFlV1GukuOmBloxKepGwYalMOqMq3Lik0qr2lsxX7Z+iADds5IaWr65sI5WDlEEBazCiAg9diQ0la8UHOOpaYRDyUFyKVCPdY5vyulnxpp1lncxO234ez64D2IXTIpS9PCJGk3H8WM5vA3rZNNSoiqjwaYNoPI5qmqUW49DeeLKeUQ+lDZS97o4V3VhBGv7WxDWFJYVFddPykRCu+GMCAwEAAaNTMFEwHQYDVR0OBBYEFCDaQ6/Lgkk2a43bTuzgbtlyHTrbMB8GA1UdIwQYMBaAFCDaQ6/Lgkk2a43bTuzgbtlyHTrbMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBACgT/c1zUSj3VIbsNRSmR9e90YWKr648S0hx2ciJTr7MPlYOzE3/+wrBul1+bjqJr6wnul1NIM3KRD733nvMKEo6BkfAtRWuQfKaYJwn6JtVBk1KYdTTFEQN5xP3WwWNP9ZaOgTBaSB7tpq4TllC20hnwQaopuRhmEDoY9bOSbVlh6sSoJvZdbphpco470FHY5kLpp/Mj/aqehQ18ADyuviJU9U0eUB+V94pkoFPywo+/C/+y3QwW8+iDCuWzaoZTHWUcBtWQYqkGFAC7XOnILORBpz6yGmMRoekUeU7a/5hstC1wToxJEHpnlAicYp9LyWVg58hUEAJUsZj2yYe7vI=
      SAML_SP_PRIVATE_KEY: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvh3tSt0n+AhqkD8ihKTUVVDf++3A4obBO0Uv9diHZ13ELvady0X2FJ6f9ZJqqHAcY6wSXwRrFM76bpbcZ8tcGtmlDTVWiFyAHNEsf3UcrsB87C4ZeNAg4orsYCWX2VzjITwhZVdRrpLjpgZaMSnqRsGGpTDqjKty4pNKq9pbMV+2fogA3bOSGlq+ubCOVg5RBAWswogIPXYkNJWvFBzjqWmEQ8lBcilQj3WOb8rpZ8aadZZ3MTtt+Hs+uA9iF0yKUvTwiRpNx/FjObwN62TTUqIqo8GmDaDyOapqlFuPQ3niynlEPpQ2Uve6OFd1YQRr+1sQ1hSWFRXXT8pEQrvhjAgMBAAECggEAaXpKezw1NHRjOe9aKq4uffCr7Yd+uik/Xz2aImdYlCVIgzumYfLNMLTR2A0ae9p30Vt42RBrW9FqWvHMA8XPvPLkclMIgGzRDEM6WZ2I5RHi0oJsbjNqNU5ki18qbEuhjY0ggT54dW74xyjeJNOkr+OD7E4odmCNXk99YMrpd0Tng+QRX8v9bHDqYufxfOnOW6Z/A8TfldZ5Ly8bUc1ybgu2KsYP9qRvgEH9VUa3TVJjdLkSUn0SL3IZ9qVLB2tf7MWOqlpSVm4+KJH6Fci6DI7YV+ZqeSAgVDt5fdpsJuW6r6T4r3wwZeOfEfN+Kbde6QZUQ0iiuq4TRrUimByCUQKBgQDnSg7n1CkBoo41YBuXn+A//S0V+8b+QHzW8xeGUHc6GvZILX59G1JoSrT4ny5pqVyYkZDW6aC1cNQG3ZAXj1VPtawZO/mDyPABqlXux6RqfZBBOPNdD5OGd/wAmiezpIk4LlsL7qe4G4pzGaQMvSWrX4v5wOzwFxMHz/zZqOHYdwKBgQDCSFeo+/bmdpOe4OWwp8fJzy4cy0Nj10NM9RCfizR7E18hJ2S59qfo59N/uoBKeaEt+2uvIsChqShZVwq8IokqK9PQniPKvOWRZ9TjFxzRYNpK+s6HdOSgvOV4bUX+skF0VEQMRetavQAfYrHbO5RxqSotIm+vWBB1cmZE+g3GdQKBgQDGyEnDSf7sXs+mZDGSwV+0313OlRRUFQy2mTtQvvuZvu6I3kDmOYM8C2k6fWUgfuUMY59+dlEfYBd6xxY+iXwjA9sj3P34G8zbQZCVppRSyhQfWlkfVHHQknLN+a/Bn9onpP+vY7BWdaUqg5EROceUYIwnXX7GYq6CemmwkIt6xQKBgG2RHt7OOo/+j4Iqk17tQF8v2HGksHy+CdZ83sMbXp2KbzvjW4sE7+0J0N1X8MIPlja4dCJxFvIU1AyOah9v2qtNzEb66HSN02oNhKINhtMOLA3dJFyAL+/2l/MyrSbWoNNaMoY5aGHj9Q2+O0/Iag8vt/l8UkAxChcyTTrZSquBAoGBAMO7t9eawGpgTcIi4E+mv5D2YkEAkiOTvjhfatCgv5OroT7kd+bGgmVpx0E8MSmZ9lCiU9M3WqF93083N2x5m9SS1k3DaffNeO55khQF1QVZmh9FA2WSp2nG64KkZ/NB+f42oce+TwXu++6vjsSZt9myb6lQZAvEoCDyuIjfm89I
      SAML_ASSERTION_CONSUMER_SERVICE_URL: http://example.local:3000/auth/callback
      SAML_SSO_URL: https://our.idp.net/saml2/idp/SSOService.php
      SAML_SLO_URL: https://our.idp.net/saml2/idp/SingleLogoutService.php
      EXPENSE_ACCOUNT: ABC12345
      CLAIM_INCOME_ACCOUNT: XYZ23456
    working_dir: /cover

  testdb:
    image: postgres:11.6
    environment:
      POSTGRES_USER: cover
      POSTGRES_PASSWORD: cover
      POSTGRES_DB: cover_test

  docs:
    build:
      context: application
      dockerfile: Dockerfile-api-docs
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      S3PATH: ${S3_PATH}

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: abc123
      MINIO_ROOT_PASSWORD: abcd1234
